### ISSUE TITLE
Add support for more vegetables

### ISSUE THREAD

**Issue by s0rthak** [carolstran/seeing-sprouts#1]
Hey,

This is a great idea! Good job with your extension!

Would you be open to accept contributions on this repo to add more vegetables? I'd like to add our (internet's) national vegetable potato and give users a dropdown to select the vegetable they'd like to see.

**Comment by neingeist** [comment]
I see the need for this, too.

**Comment by carolstran** [comment]
Never thought anyone would actually use this but if the people want more vegetables, then that's what we should give them 🤣 

Go for it 🥔🌽🥒🍆🥕🍠 🚀

**Comment by s0rthak** [comment]
Hey!

I added a PR with support for potatoes [link](https://github.com/carolstran/seeing-sprouts/pull/3)
