### ISSUE TITLE
Bug: artichokes are not sprouts

### ISSUE THREAD

**Issue by stereobooster** [carolstran/seeing-sprouts#7]
<img width="219" alt="Screenshot 2019-06-30 at 16 05 23" src="https://user-images.githubusercontent.com/179534/60397788-eac55280-9b50-11e9-93fe-add4facd35b1.png">

**Comment by carolstran** [comment]
Hahahaahaaaaaa tbh I've never seen the inside of a brussel sprout 🙈

**Comment by carolstran** [comment]
Or an artichoke now that I think about it... only on pizza 😂

**Comment by carolstran** [comment]
But ok thanks for the alert @stereobooster, will be sure to fix this super urgent bug asap 👩‍🚒

**Comment by stereobooster** [comment]
> Or an artichoke now that I think about it... 

We need to fix this

**Comment by carolstran** [comment]
Fixed it 😇 https://github.com/carolstran/seeing-sprouts/commit/f038f3cf2895f9db575dd36db349f74648ebee71

**Comment by stereobooster** [comment]
the best open source maintainer ever 👌. Bug was addressed so fast 🙇
